BetaAirlinesMVC/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BetaAirlinesMVC.Models;

namespace BetaAirlinesMVC.Controllers
{
    public class ContactController : Controller
    {
        private BetaAirlinesDbContext db = new BetaAirlinesDbContext();

        // GET: Contacts/Index (to create new message)
        public ActionResult Index()
        {
            Contact model = new Contact();

            // set default values for the form
            model.Date = DateTime.Today;
            model.Active = 1;

            return View(model);
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "Id,Name,Email,Subject,Message,Date,Active")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Contacts.Add(contact);
                db.SaveChanges();
                return RedirectToAction("Confirmation");
            }

            return View(contact);
        }

        // GET: Contacts/MessageConfirmation
        public ActionResult Confirmation()
        {
            return View();
        }

        // GET: Contacts
        public ActionResult Messages()
        {
            return View(db.Contacts.ToList());
        }

        // GET: Contacts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: Contacts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Email,Subject,Message,Date,Active")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contact contact = db.Contacts.Find(id);
            db.Contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BetaAirlinesMVC/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BetaAirlinesMVC.Models;
using BetaAirlinesMVC.ViewModel;
using BetaAirlinesMVC.Utilities;

namespace BetaAirlinesMVC.Controllers
{
    // Uses BetaAirlinesMVC.Utilities to run a SessionCheck
    // Having it here runs the session check in all actions on this controller
    // Else place it only on the actions that you want it on
    [SessionCheck]
    public class FlightsController : Controller
    {
        private BetaAirlinesDbContext db = new BetaAirlinesDbContext();
        private DataValidation dv = new DataValidation();

        // GET: Flights
        public ActionResult Index()
        {


            var flights = db.Flights.Include(f => f.ArrivalAirport).Include(f => f.DepartureAirport).OrderBy(f=>f.DepartureDate);
            return View(flights.ToList());
        }

        // GET: Flights/Details/5
        public ActionResult Details(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // GET: Flights/Create
        public ActionResult Create()
        {


            ViewBag.ArrivalAirportId = new SelectList(db.Airports, "Id", "Name");
            ViewBag.DepartureAirportId = new SelectList(db.Airports, "Id", "Name");
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DepartureDate,DepartureAirportId,ArrivalAirportId,FlightLengthInMinutes,Active")] Flight flight)
        {


            if (ModelState.IsValid)
            {
                db.Flights.Add(flight);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArrivalAirportId = new SelectList(db.Airports, "Id", "Name", flight.ArrivalAirportId);
            ViewBag.DepartureAirportId = new SelectList(db.Airports, "Id", "Name", flight.DepartureAirportId);
            return View(flight);
        }

        // GET: Flights/Edit/5
        public ActionResult Edit(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArrivalAirportId = new SelectList(db.Airports, "Id", "Name", flight.ArrivalAirportId);
            ViewBag.DepartureAirportId = new SelectList(db.Airports, "Id", "Name", flight.DepartureAirportId);
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DepartureDate,DepartureAirportId,ArrivalAirportId,FlightLengthInMinutes,Active")] Flight flight)
        {


            if (ModelState.IsValid)
            {
                db.Entry(flight).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArrivalAirportId = new SelectList(db.Airports, "Id", "Name", flight.ArrivalAirportId);
            ViewBag.DepartureAirportId = new SelectList(db.Airports, "Id", "Name", flight.DepartureAirportId);
            return View(flight);
        }

        // GET: Flights/Delete/5
        public ActionResult Delete(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {


            Flight flight = db.Flights.Find(id);
            db.Flights.Remove(flight);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        // Book A Flight
        [HttpGet]
        public ActionResult BookAFlight(int? dpt, int? arr)
        {

            BookAFlightViewModel model = new BookAFlightViewModel();

            try
            {
                // Get all the list of airports
                ViewBag.dpt = new SelectList(db.Airports, "Id", "Name"); // Departure
                ViewBag.arr = new SelectList(db.Airports, "Id", "Name"); // Arrival
                ViewBag.UserID = Session["id"];

                // Get the list of predetermined flights for the user to choose from
                if (dpt != null && arr != null)
                {
                    model.FlightList = new List<Flight>(db.Flights.Where(x => x.DepartureAirportId == dpt && x.ArrivalAirportId == arr).OrderBy(x => x.DepartureDate));
                }
                else if ((dpt != null && arr == null) || (dpt == null && arr != null))
                {
                    model.FlightList = new List<Flight>(db.Flights.Where(x => x.DepartureAirportId == dpt || x.ArrivalAirportId == arr).OrderBy(x => x.DepartureDate));
                }
                else
                {
                    model.FlightList = db.Flights.ToList();
                    model.FlightList.OrderBy(x => x.DepartureDate);
                }
            } catch(Exception ex)
            {
                model = null;
            }

            return View(model);
        }
    }
}

BetaAirlinesMVC/Views/Shared/_BetaAirlinesLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Beta Airlines MVC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <img src="~/Content/images/BetaAirline_CompanyLogo.png" alt="Beta Airlines with logo" title="Beta Airlines Company Logo" />
        <nav id="mainNav">
            <div id="MainNavigation">
                <ul class="level1" tabindex="0">
                    <li>@Html.ActionLink("Home", "Index", "Home", null, new { title = "The home page of the website", @class = "level1" })</li>
                    <li>@Html.ActionLink("Plan a Trip", "Plan", "Home", null, new { title = "Plan a Trip" })</li>
                    @if (Session != null && (string)Session["role"] == "Admin")
                    {
                        <li>@Html.ActionLink("Admin Page", "Index", "Admin", null, new { title = "Admin" })</li>
                    }
                    else if (Session != null && (string)Session["role"] == "Manager")
                    {
                        <li>@Html.ActionLink("Management Page", "Index", "Manage", null, new { title = "Admin" })</li>
                    }
                    else
                    {
                    <li>@Html.ActionLink("Book a Flight", "BookAFlight", "Flights", null, new { title = "Book a Flight" })</li>
                    }
                    <li>@Html.ActionLink("Contact Us", "Index", "Contact", null, new { title = "A contact form to ask us a question or provide feedback." })</li>
                    @if (Session != null && Session["id"] != null && Session["pw"] != null)
                    {
                        <li>@Html.ActionLink("Logout", "Login", "Users", null, new { title = "Logout" })</li>
                    }
                </ul>
            </div><div style="clear:left;"></div>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        <p><small>Copyright &copy; Beta Airlines 2021 - MVC Website by David Oberlander</small></p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/myScripts")
    @RenderSection("scripts", required: false)
</body>
</html>

BetaAirlinesMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Beta Airlines - MVC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</body>
</html>