BetaAirlinesMVC/Models/Flight.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BetaAirlinesMVC.Models
{
    [Table("Flights")]
    public class Flight
    {
        [Key]
        public int Id { get; set; }

        [Display(Name ="Departure Date")]
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DepartureDate { get; set; }

        [Display(Name = "Departure Airport")]
        [Required]
        [ForeignKey("DepartureAirport")]
        public int DepartureAirportId { get; set; }
        
        public virtual Airport DepartureAirport { get; set; }

        [Required]
        [ForeignKey("ArrivalAirport")]
        [Display(Name = "Arrival Airport")]
        public int ArrivalAirportId { get; set; }

        public virtual Airport ArrivalAirport { get; set; }

        [Display(Name ="Duration")]
        [Range(0,5000)]
        public int FlightLengthInMinutes { get; set; }

        [DefaultValue(1)]
        public int Active { get; set; }
    }
}

BetaAirlinesMVC/Controllers/BookedFlightsController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BetaAirlinesMVC.Models;
using BetaAirlinesMVC.Utilities;
using BetaAirlinesMVC.ViewModel;

namespace BetaAirlinesMVC.Controllers
{

    // Uses BetaAirlinesMVC.Utilities to run a SessionCheck
    // Having it here runs the session check in all actions on this controller
    // Else place it only on the actions that you want it on
    [SessionCheck]
    public class BookedFlightsController : Controller
    {
        private BetaAirlinesDbContext db = new BetaAirlinesDbContext();

        [HttpGet]
        public ActionResult Index()
        {
            List<MyFlightsViewModel> yourFlights = new List<MyFlightsViewModel>();

            try { 
            int loggedInUser = (int)Session["id"];
            foreach (var flight in db.BookedFlights.Where(x => x.UserId == loggedInUser).OrderBy(x => x.DateBooked))
                {
                    // Get flight data
                    Flight flights = db.Flights.Where(x => x.Id == flight.FlightId).SingleOrDefault();
                    User theUser = db.Users.Where(u => u.Id == flight.UserId).SingleOrDefault();
                    Airport depAirport = db.Airports.Where(a => a.Id == flights.DepartureAirportId).SingleOrDefault();
                    Airport arrAirport = db.Airports.Where(a => a.Id == flights.ArrivalAirportId).SingleOrDefault();

                    // Create my flight object
                    MyFlightsViewModel mfvm = new MyFlightsViewModel();
                    mfvm.Id = flight.Id;
                    mfvm.UserId = flight.UserId;
                    mfvm.FirstName = theUser.FirstName;
                    mfvm.LastName = theUser.LastName;
                    mfvm.DepartureDate = flights.DepartureDate;
                    mfvm.DepartureAirport = depAirport.Name;
                    mfvm.ArrivalAirport = arrAirport.Name;
                    mfvm.ActiveBookedFlight = flight.Active;
                    


                    yourFlights.Add(mfvm);
                }
            } catch (Exception ex)
            {
                yourFlights = null;
                ViewBag.AlertMessage = "You have no booked flights.";
            }

            return View(yourFlights);
        }

        // GET: BookedFlights
        public ActionResult Admin()
        {
            var bookedFlights = db.BookedFlights.Include(b => b.Flight).Include(b => b.BookedUserId).OrderBy(x => x.DateBooked);
            return View(bookedFlights.ToList());
        }

        // GET: BookedFlights/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookedFlight bookedFlight = db.BookedFlights.Find(id);
            if (bookedFlight == null)
            {
                return HttpNotFound();
            }
            return View(bookedFlight);
        }

        // GET: BookedFlights/Create
        public ActionResult Create()
        {
            ViewBag.FlightId = new SelectList(db.Flights, "Id", "Id");
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: BookedFlights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int usr, int fid, [Bind(Include = "Id,DateBooked,Active,UserId,FlightId")] BookedFlight bookedFlight)
        {
            if (ModelState.IsValid)
            {
                if(fid != null)
                {
                    bookedFlight.DateBooked = DateTime.Now;
                    bookedFlight.FlightId = fid;
                    bookedFlight.UserId = usr;
                    bookedFlight.Active = 1; // Default is active
                }
                db.BookedFlights.Add(bookedFlight);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FlightId = new SelectList(db.Flights, "Id", "Id", bookedFlight.FlightId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", bookedFlight.UserId);
            return View(bookedFlight);
        }


        // GET: BookedFlights/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookedFlight bookedFlight = db.BookedFlights.Find(id);
            if (bookedFlight == null)
            {
                return HttpNotFound();
            }
            ViewBag.FlightId = new SelectList(db.Flights, "Id", "Id", bookedFlight.FlightId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", bookedFlight.UserId);
            return View(bookedFlight);
        }

        // POST: BookedFlights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DateBooked,Active,UserId,FlightId")] BookedFlight bookedFlight)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bookedFlight).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FlightId = new SelectList(db.Flights, "Id", "Id", bookedFlight.FlightId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", bookedFlight.UserId);
            return View(bookedFlight);
        }

        // GET: BookedFlights/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookedFlight bookedFlight = db.BookedFlights.Find(id);
            if (bookedFlight == null)
            {
                return HttpNotFound();
            }
            return View(bookedFlight);
        }

        // POST: BookedFlights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BookedFlight bookedFlight = db.BookedFlights.Find(id);
            db.BookedFlights.Remove(bookedFlight);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BetaAirlinesMVC/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BetaAirlinesMVC.Models;
using BetaAirlinesMVC.ViewModel;
using BetaAirlinesMVC.Utilities;

namespace BetaAirlinesMVC.Controllers
{
    // Uses BetaAirlinesMVC.Utilities to run a SessionCheck
    // Having it here runs the session check in all actions on this controller
    // Else place it only on the actions that you want it on
    [SessionCheck]
    public class FlightsController : Controller
    {
        private BetaAirlinesDbContext db = new BetaAirlinesDbContext();
        private DataValidation dv = new DataValidation();

        // GET: Flights
        public ActionResult Index()
        {


            var flights = db.Flights.Include(f => f.ArrivalAirport).Include(f => f.DepartureAirport).OrderBy(f=>f.DepartureDate);
            return View(flights.ToList());
        }

        // GET: Flights/Details/5
        public ActionResult Details(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // GET: Flights/Create
        public ActionResult Create()
        {


            ViewBag.ArrivalAirportId = new SelectList(db.Airports, "Id", "Name");
            ViewBag.DepartureAirportId = new SelectList(db.Airports, "Id", "Name");
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DepartureDate,DepartureAirportId,ArrivalAirportId,FlightLengthInMinutes,Active")] Flight flight)
        {


            if (ModelState.IsValid)
            {
                db.Flights.Add(flight);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArrivalAirportId = new SelectList(db.Airports, "Id", "Name", flight.ArrivalAirportId);
            ViewBag.DepartureAirportId = new SelectList(db.Airports, "Id", "Name", flight.DepartureAirportId);
            return View(flight);
        }

        // GET: Flights/Edit/5
        public ActionResult Edit(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArrivalAirportId = new SelectList(db.Airports, "Id", "Name", flight.ArrivalAirportId);
            ViewBag.DepartureAirportId = new SelectList(db.Airports, "Id", "Name", flight.DepartureAirportId);
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DepartureDate,DepartureAirportId,ArrivalAirportId,FlightLengthInMinutes,Active")] Flight flight)
        {


            if (ModelState.IsValid)
            {
                db.Entry(flight).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArrivalAirportId = new SelectList(db.Airports, "Id", "Name", flight.ArrivalAirportId);
            ViewBag.DepartureAirportId = new SelectList(db.Airports, "Id", "Name", flight.DepartureAirportId);
            return View(flight);
        }

        // GET: Flights/Delete/5
        public ActionResult Delete(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {


            Flight flight = db.Flights.Find(id);
            db.Flights.Remove(flight);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        // Book A Flight
        [HttpGet]
        public ActionResult BookAFlight(int? dpt, int? arr)
        {

            BookAFlightViewModel model = new BookAFlightViewModel();

            try
            {
                // Get all the list of airports
                ViewBag.dpt = new SelectList(db.Airports, "Id", "Name"); // Departure
                ViewBag.arr = new SelectList(db.Airports, "Id", "Name"); // Arrival
                ViewBag.UserID = Session["id"];

                // Get the list of predetermined flights for the user to choose from
                if (dpt != null && arr != null)
                {
                    model.FlightList = new List<Flight>(db.Flights.Where(x => x.DepartureAirportId == dpt && x.ArrivalAirportId == arr).OrderBy(x => x.DepartureDate));
                }
                else if ((dpt != null && arr == null) || (dpt == null && arr != null))
                {
                    model.FlightList = new List<Flight>(db.Flights.Where(x => x.DepartureAirportId == dpt || x.ArrivalAirportId == arr).OrderBy(x => x.DepartureDate));
                }
                else
                {
                    model.FlightList = db.Flights.ToList();
                    model.FlightList.OrderBy(x => x.DepartureDate);
                }
            } catch(Exception ex)
            {
                model = null;
            }

            return View(model);
        }
    }
}

BetaAirlinesMVC/Views/Flights/BookAFlight.cshtml
@model BetaAirlinesMVC.ViewModel.BookAFlightViewModel
@using BetaAirlinesMVC.Utilities;

@{
    ViewBag.Title = "Book A Flight";
    Layout = "~/Views/Shared/_BetaAirlinesLayout.cshtml";
}

<section class="content flexcolumn">
    <h2>@ViewBag.Title</h2>

    <p>
        @Html.ActionLink("My Flights", "Index", "BookedFlights")
    </p>

    @using (Html.BeginForm("BookAFlight", "Flights", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Get))
    {
        @Html.DropDownList("dpt", null, "-- Departure Flight --", htmlAttributes: new { @class = "form-control dropdown" })
        @Html.DropDownList("arr", null, "-- Arrival Flight --", htmlAttributes: new { @class = "form-control dropdown" })
        <input type="submit" value="Search" />
    }
    <table>
        <tr class="row">
            <th>
                Departure Airport
            </th>
            <th>
                Arrival Airport
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightLengthInMinutes)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.FlightList)
        {
            <tr class="row">
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureAirport.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArrivalAirport.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureDate)
                </td>
                <td>
                    @{
                        TimeConversion timeConversion = new TimeConversion();
                        string duration = timeConversion.GetDuration(item.FlightLengthInMinutes);
                    }
                    @Html.DisplayFor(modelItem => duration)
                </td>
                <td>
                    @using (Html.BeginForm("Create", "BookedFlights", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" value="@ViewBag.UserID" name="usr" />

                        <input type="hidden" value="@item.Id" name="fid" />
                        <input type="submit" value="Book Flight" class="btn btn-primary" />
                    }
                </td>
            </tr>
        }

    </table>
    @ViewBag.Test
    <div class="backLink">
        @Html.ActionLink("Logout", "Logout", "Users")
    </div>

</section>

BetaAirlinesMVC/Views/Flights/Create.cshtml
@model BetaAirlinesMVC.Models.Flight

@{
    ViewBag.Title = "Create Flight";
    Layout = "~/Views/Shared/_BetaAirlinesLayout.cshtml";
}

<section class="content flexcolumn">
    <h2>@ViewBag.Title</h2>


    @using (Html.BeginForm("Create", "Flights", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "forms" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DepartureDate, htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7 formInputDiv">
                    @Html.EditorFor(model => model.DepartureDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DepartureDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DepartureAirportId, "DepartureAirportId", htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7 formInputDiv">
                    @Html.DropDownList("DepartureAirportId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DepartureAirportId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ArrivalAirportId, "ArrivalAirportId", htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7 formInputDiv">
                    @Html.DropDownList("ArrivalAirportId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ArrivalAirportId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FlightLengthInMinutes, htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7 formInputDiv">
                    @Html.EditorFor(model => model.FlightLengthInMinutes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FlightLengthInMinutes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7 formInputDiv">
                    @Html.DropDownListFor(model => model.Active, new[] { new SelectListItem { Text = "True (1)", Value = "1" }, new SelectListItem { Text = "False (0)", Value = "0" } }, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div>
                    <input type="submit" value="Create Flight" class="btn btn-warning linkDark" />
                </div>
            </div>
        </div>
    }

    <div class="backLink">
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</section>

BetaAirlinesMVC/Views/Flights/Delete.cshtml
@model BetaAirlinesMVC.Models.Flight

@{
    ViewBag.Title = "Delete Flight";
    Layout = "~/Views/Shared/_BetaAirlinesLayout.cshtml";
}

<section class="content flexcolumn">
    <h2>@ViewBag.Title</h2>
    <h4>Are you sure you want to delete this?</h4>
    <div class="text-left">
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ArrivalAirport.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ArrivalAirport.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DepartureAirport.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DepartureAirport.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DepartureDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DepartureDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FlightLengthInMinutes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FlightLengthInMinutes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Active)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Active)
            </dd>

        </dl>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
    <div class="backLink">
        @Html.ActionLink("Back to List", "Index")
    </div>

</section>

BetaAirlinesMVC/Views/Flights/Details.cshtml
@model BetaAirlinesMVC.Models.Flight

@{
    ViewBag.Title = "Flight Details";
    Layout = "~/Views/Shared/_BetaAirlinesLayout.cshtml";
}

<section class="content flexcolumn">
    <h2>@ViewBag.Title</h2>

    <div class="text-left">
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ArrivalAirport.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ArrivalAirport.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DepartureAirport.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DepartureAirport.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DepartureDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DepartureDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FlightLengthInMinutes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FlightLengthInMinutes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Active)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Active)
            </dd>

        </dl>
    </div>
    <div class="form-group">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.ActionLink("Edit Flight", "Edit", new { id = Model.Id })
        }
    </div>
    <div class="backLink">
        @Html.ActionLink("Back to List", "Index")
    </div>
</section>

BetaAirlinesMVC/Views/Flights/Edit.cshtml
@model BetaAirlinesMVC.Models.Flight

@{
    ViewBag.Title = "Edit Flight";
    Layout = "~/Views/Shared/_BetaAirlinesLayout.cshtml";
}

<section class="content flexcolumn">
    <h2>@ViewBag.Title</h2>


    @using (Html.BeginForm("Edit", "Flights", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "forms" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.DepartureDate, htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7">
                    @Html.EditorFor(model => model.DepartureDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DepartureDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DepartureAirportId, "DepartureAirportId", htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7">
                    @Html.DropDownList("DepartureAirportId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DepartureAirportId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ArrivalAirportId, "ArrivalAirportId", htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7">
                    @Html.DropDownList("ArrivalAirportId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ArrivalAirportId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FlightLengthInMinutes, htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7">
                    @Html.EditorFor(model => model.FlightLengthInMinutes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FlightLengthInMinutes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7">
                    @Html.DropDownListFor(model => model.Active, new[] { new SelectListItem { Text = "True (1)", Value = "1" }, new SelectListItem { Text = "False (0)", Value = "0" } }, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div>
                    <input type="submit" value="Save" class="btn btn-warning linkDark" />
                </div>
            </div>
        </div>
    }

    <div class="backLink">
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</section>

BetaAirlinesMVC/Views/Flights/Index.cshtml
@model IEnumerable<BetaAirlinesMVC.Models.Flight>

@{
    ViewBag.Title = "Flights";
    Layout = "~/Views/Shared/_BetaAirlinesLayout.cshtml";
}

<section class="content flexcolumn">
    <h2>@ViewBag.Title</h2>
    <p>
        @Html.ActionLink("Add New Flight", "Create")
    </p>
    <table>
        <tr>
            <th>
                Departure Airport
            </th>
            <th>
                Arrival Airport
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightLengthInMinutes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureAirport.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArrivalAirport.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightLengthInMinutes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td class="buttons">
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</section>